[env:esp12e]
platform = espressif8266@4.2.1
framework = arduino
board = esp12e
board_build.f_cpu = 160000000L
board_build.flash_mode = dio
monitor_speed = 115200
upload_speed = 460800
extra_scripts = pre:scripts/set_version.py
build_flags =
    -Wl,-Teagle.flash.4m2m.ld
lib_deps =
    miguelbalboa/MFRC522@^1.4.11
    bblanchon/ArduinoJson@^6.21.5
